Add the examples link to readme again
muxinc/media-chrome pull request #111
Opened 2022-01-12 18:08 UTC by luwes

Wasn't really sure where to put it. Feel free to make suggestions

2022-01-14 13:20 UTC, cjpillsbury requested changes
Thanks!

2022-01-14 13:20 UTC, cjpillsbury commented on README.md
> +<a href="https://media-chrome.mux.dev/examples/" target="_blank">View more examples</a>
I actually just re-hunted down this URL yesterday for a discussion with someone lol. I'm also not sure where to put this. Let's keep it here for now but give it a little more attention
* make text larger
* Change text to say something like (?)
  > See all of the repo examples in action.

2022-01-23 00:52 UTC, heff approved these changes

2022-01-23 00:56 UTC, heff commented
@cjpillsbury looks like Wes made the changes and it needs your review to merge.

2022-01-23 14:27 UTC, cjpillsbury approved these changes

2022-01-23 14:27 UTC, merged