Add max/min css vars for the thumb previews
muxinc/media-chrome pull request #179
Opened 2022-03-07 00:06 UTC by luwes

Related to https://github.com/muxinc/media-chrome/pull/171

Adds a configurable max and min width for the thumb preview.
This uses a CSS transform: scale() to up and down scale to the max and min width via JS if needed. A small down side is that the border also scales with that, this is solved by setting each CSS property again with the scale factored in with JS.

Also changed the positioning via `style.left` to `style.transform = translate` because this should perform better.
https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/

Fixes 2 small issues;

- bottom black border in thumb preview
- fading out animation did not work because of the CSS display prop

2022-03-11 06:21 UTC, dylanjha commented
I found that the thumbnails were a bit small on stream.new, especially noticeable in a large viewport. Having some solution for that makes a lot of sense.

As far as the actual approach, `--media-thumbnail-preview-min-width` and `--media-thumbnail-preview-max-width` make sense 👍🏼 

Are there any gotchas or caveats when using these variables with vertically orientated videos?

2022-03-12 15:42 UTC, luwes commented
@dylanjha good call, we might have to find a solution for vertical videos. Add min / max height vars too?

2022-04-07 17:02 UTC, cjpillsbury commented on examples/vertical.html
> +<!DOCTYPE html>
good example add, even without the thumbnails 👌

2022-04-07 17:04 UTC, cjpillsbury commented on src/js/media-time-range.js
> +      transition: visibility .5s, opacity .5s;
👌

2022-04-07 17:06 UTC, gkatsev commented on src/js/media-time-range.js
> +      border-right: 10px solid transparent;
non-blocking: you can also use [`border-inline`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline) to have this as one item.

2022-04-07 17:20 UTC, cjpillsbury requested changes
blocker: Make sure you update the relevant docs.
at least before smoke testing, code LGTM

2022-05-10 14:49 UTC, cjpillsbury approved these changes
👌

2022-05-10 15:44 UTC, merged