doc: Manual version bump to 0.17
muxinc/media-chrome pull request #419
Opened 2023-01-06 23:54 UTC by heff

Also added more specific versions for a few projects where needed.

2023-01-06 23:55 UTC, heff commented on package.json
> +  "version": "0.17.0",
Shouldn't this have happened as part of the conventional CD?

2023-01-06 23:55 UTC, cjpillsbury approved these changes
🚢 🇮🇹

2023-01-07 00:00 UTC, luwes requested changes
use tag commits

2023-01-07 00:14 UTC, luwes approved these changes

2023-01-07 00:16 UTC, merged