feat: icon slots for single slot controls
muxinc/media-chrome pull request #645
Opened 2023-05-25 09:15 UTC by AdamJaggard

Replaces the single named slot in controls with a generic one called "icon". Affects Airplay, Seek forwards and backwards buttons.

This is a breaking change.

2023-05-25 12:54 UTC, luwes approved these changes

2023-05-26 16:49 UTC, luwes commented
> This is a breaking change.

### Remember to add to the upgrade guide 

https://github.com/muxinc/media-chrome/blob/main/docs/src/pages/en/migration/from-0.x-to-1.0.md

2023-05-26 16:51 UTC, gkatsev commented
And add `BREAKING CHANGE: ...` in the footer of the commit when merging.

2023-05-30 18:25 UTC, cjpillsbury commented on docs/src/pages/docs/en/migration/from-0.x-to-1.0.md
> +All components with a single icon now expose a slot called `icon` instead of a different named slot for each component. e.g:
suggestion(non-blocking): Consider adding a simple list here of all of the single element slot renames, similar to https://github.com/muxinc/media-chrome/blob/main/docs/src/pages/docs/en/migration/from-0.x-to-1.0.md?plain=1#L165-L169)

2023-05-30 18:28 UTC, cjpillsbury requested changes
This looks great overall. A couple of suggestions on the docs side plus:
issue(blocking): rename `media-loading-indicator` icon slot for consistency.

2023-05-30 18:50 UTC, cjpillsbury commented on docs/src/pages/docs/en/migration/from-0.x-to-1.0.md
> +**Affected components**
👍

2023-05-30 18:50 UTC, cjpillsbury approved these changes
🥳

2023-05-30 18:54 UTC, merged